runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /.*
  script: main.app


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env$ #virtual environment's folder
