runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: '2.5.2'

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env$ #virtual environment's folder
